// The app tables' migrations (./migrations, generated by drizzle-kit from
// ./schema.ts), in the order drizzle-kit's journal gives them. `pnpm run
// seed:dev` applies them to the local `APP_DB` with `wrangler d1 migrations
// apply`, which reads this folder through web/wrangler.jsonc's
// `migrations_dir`, and every test that needs the app database builds it
// through applyAppMigrations.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const FOLDER = new URL("./migrations/", import.meta.url);

interface Journal {
  entries: { idx: number; tag: string }[];
}

/** The absolute path of each migration's SQL, oldest first. */
export function appMigrationFiles(): readonly string[] {
  const journal = JSON.parse(readFileSync(new URL("meta/_journal.json", FOLDER), "utf8")) as Journal;
  return [...journal.entries]
    .sort((a, b) => a.idx - b.idx)
    .map(({ tag }) => fileURLToPath(new URL(`${tag}.sql`, FOLDER)));
}

/**
 * Apply every migration to an empty database, which becomes the app database.
 * drizzle-kit's `--> statement-breakpoint` markers are SQL comments, so each
 * file runs as it stands.
 */
export function applyAppMigrations(db: { exec(sql: string): void }): void {
  for (const path of appMigrationFiles()) db.exec(readFileSync(path, "utf8"));
}
