// THE ANSWER TO "how do I reach a D1 binding from server code in vinext":
// there is no vinext-specific helper and no getCloudflareContext(). You import
// the Workers runtime's own `env`, which @cloudflare/vite-plugin also provides
// in dev. `env` is typed as Env, generated by `pnpm exec wrangler types`.
import { env } from "cloudflare:workers";

export type SpikeWord = {
  id: number;
  lemma: string;
  pos: string;
  gloss: string;
};

export async function findByLemma(lemma: string): Promise<SpikeWord[]> {
  const { results } = await env.DB.prepare(
    "SELECT id, lemma, pos, gloss FROM spike_words WHERE lemma = ? ORDER BY id",
  )
    .bind(lemma)
    .all<SpikeWord>();

  return results;
}
