-- Generated by drizzle-kit from src/db/app/schema.ts (#228), then edited by
-- hand so each table keeps the exact shape src/db/schema.sql gave it
-- (test/appSchema.test.ts holds it there):
--   * every table is STRICT, which Drizzle cannot declare;
--   * a single-column PRIMARY KEY carries no NOT NULL, as before;
--   * the two UNIQUE constraints stay inline, so SQLite names their indexes
--     sqlite_autoindex_api_key_1 and sqlite_autoindex_provider_identity_1, which
--     the query plans in test/accounts.test.ts and test/apiKeys.test.ts name.
-- drizzle-kit's snapshot in ./meta still records what it generated.
CREATE TABLE `api_key` (
	`key_id` integer PRIMARY KEY,
	`key_hash` text NOT NULL UNIQUE,
	`label` text NOT NULL,
	`per_minute_limit` integer,
	`created_at` text NOT NULL,
	`revoked_at` text,
	`owner_account_id` integer,
	`display_prefix` text NOT NULL,
	`last_used_at` text,
	`endpoints` text,
	`expires_at` text,
	FOREIGN KEY (`owner_account_id`) REFERENCES `developer_account`(`account_id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "api_key_hash" CHECK(length(key_hash) = 64),
	CONSTRAINT "api_key_label" CHECK(length(label) BETWEEN 1 AND 200),
	CONSTRAINT "api_key_per_minute_limit" CHECK(per_minute_limit > 0),
	CONSTRAINT "api_key_display_prefix" CHECK(display_prefix GLOB 'lx_[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]'),
	CONSTRAINT "api_key_endpoints" CHECK(endpoints IS NULL OR (json_valid(endpoints) AND json_type(endpoints) = 'array' AND json_array_length(endpoints) >= 1)),
	CONSTRAINT "api_key_owned_or_limited" CHECK((owner_account_id IS NULL) = (per_minute_limit IS NOT NULL))
) STRICT;
--> statement-breakpoint
CREATE INDEX `api_key_by_owner` ON `api_key` (`owner_account_id`);--> statement-breakpoint
CREATE TABLE `api_key_minute` (
	`key_id` integer NOT NULL,
	`minute` integer NOT NULL,
	`requests` integer NOT NULL,
	PRIMARY KEY(`key_id`, `minute`),
	FOREIGN KEY (`key_id`) REFERENCES `api_key`(`key_id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "api_key_minute_requests" CHECK(requests > 0)
) STRICT;
--> statement-breakpoint
CREATE TABLE `api_key_usage` (
	`key_id` integer NOT NULL,
	`day` text NOT NULL,
	`calls` integer NOT NULL,
	PRIMARY KEY(`key_id`, `day`),
	FOREIGN KEY (`key_id`) REFERENCES `api_key`(`key_id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "api_key_usage_day" CHECK(day GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
	CONSTRAINT "api_key_usage_calls" CHECK(calls >= 0)
) STRICT;
--> statement-breakpoint
CREATE TABLE `developer_account` (
	`account_id` integer PRIMARY KEY,
	`created_at` text NOT NULL,
	`deleted_at` text
) STRICT;
--> statement-breakpoint
CREATE TABLE `developer_session` (
	`session_hash` text PRIMARY KEY,
	`account_id` integer NOT NULL,
	`created_at` text NOT NULL,
	`expires_at` text NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `developer_account`(`account_id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "developer_session_hash" CHECK(length(session_hash) = 64)
) STRICT;
--> statement-breakpoint
CREATE INDEX `developer_session_by_expiry` ON `developer_session` (`expires_at`);--> statement-breakpoint
CREATE INDEX `developer_session_by_account` ON `developer_session` (`account_id`);--> statement-breakpoint
CREATE TABLE `provider_identity` (
	`identity_id` integer PRIMARY KEY,
	`account_id` integer NOT NULL,
	`provider` text NOT NULL,
	`provider_user_id` text NOT NULL,
	`email` text NOT NULL,
	`display_name` text,
	`linked_at` text NOT NULL,
	CONSTRAINT "provider_identity_provider_user" UNIQUE(`provider`,`provider_user_id`),
	FOREIGN KEY (`account_id`) REFERENCES `developer_account`(`account_id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "provider_identity_provider" CHECK(provider IN ('google', 'github')),
	CONSTRAINT "provider_identity_provider_user_id" CHECK(length(provider_user_id) > 0),
	CONSTRAINT "provider_identity_email" CHECK(email = lower(email) AND email LIKE '%_@_%'),
	CONSTRAINT "provider_identity_display_name" CHECK(display_name IS NULL OR length(trim(display_name)) > 0)
) STRICT;
--> statement-breakpoint
CREATE INDEX `provider_identity_by_email` ON `provider_identity` (`email`);--> statement-breakpoint
CREATE INDEX `provider_identity_by_account` ON `provider_identity` (`account_id`);
