-- Generated by drizzle-kit from src/db/app/schema.ts (#229): the account,
-- identity and session tables become better-auth's, under Lexema's names, and
-- better-auth's `verification` table is added (ADR 0017). Then edited by hand:
--   * every table it creates is STRICT, which Drizzle cannot declare;
--   * the rebuilt tables start empty. drizzle-kit copied each old row into the
--     new table, but the old rows have no email, name or token to copy, and
--     ADR 0017 re-makes local accounts rather than migrating them: run
--     `pnpm run seed:dev`, which rebuilds the database, and sign in again;
--   * drizzle-kit's `PRAGMA foreign_keys` switches are gone: nothing is copied,
--     so no row can break a foreign key, and each table is dropped while empty.
-- drizzle-kit's snapshot in ./meta still records what it generated.
CREATE TABLE `verification` (
	`verification_id` integer PRIMARY KEY NOT NULL,
	`identifier` text NOT NULL,
	`value` text NOT NULL,
	`expires_at` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
) STRICT;
--> statement-breakpoint
CREATE INDEX `verification_by_identifier` ON `verification` (`identifier`);--> statement-breakpoint
CREATE INDEX `verification_by_expiry` ON `verification` (`expires_at`);--> statement-breakpoint
CREATE TABLE `__new_developer_session` (
	`session_id` integer PRIMARY KEY NOT NULL,
	`token` text NOT NULL,
	`account_id` integer NOT NULL,
	`expires_at` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`ip_address` text,
	`user_agent` text,
	FOREIGN KEY (`account_id`) REFERENCES `developer_account`(`account_id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "developer_session_client" CHECK(ip_address IS NULL AND user_agent IS NULL)
) STRICT;
--> statement-breakpoint
DROP TABLE `developer_session`;--> statement-breakpoint
ALTER TABLE `__new_developer_session` RENAME TO `developer_session`;--> statement-breakpoint
CREATE UNIQUE INDEX `developer_session_token_unique` ON `developer_session` (`token`);--> statement-breakpoint
CREATE INDEX `developer_session_by_expiry` ON `developer_session` (`expires_at`);--> statement-breakpoint
CREATE INDEX `developer_session_by_account` ON `developer_session` (`account_id`);--> statement-breakpoint
CREATE TABLE `__new_provider_identity` (
	`identity_id` integer PRIMARY KEY NOT NULL,
	`account_id` integer NOT NULL,
	`provider` text NOT NULL,
	`provider_user_id` text NOT NULL,
	`email` text NOT NULL,
	`display_name` text,
	`linked_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`access_token` text,
	`refresh_token` text,
	`id_token` text,
	`access_token_expires_at` text,
	`refresh_token_expires_at` text,
	`scope` text,
	`password` text,
	FOREIGN KEY (`account_id`) REFERENCES `developer_account`(`account_id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "provider_identity_provider" CHECK(provider IN ('google', 'github')),
	CONSTRAINT "provider_identity_provider_user_id" CHECK(length(provider_user_id) > 0),
	CONSTRAINT "provider_identity_email" CHECK(email = lower(email) AND email LIKE '%_@_%'),
	CONSTRAINT "provider_identity_display_name" CHECK(display_name IS NULL OR length(trim(display_name)) > 0),
	CONSTRAINT "provider_identity_no_credentials" CHECK(access_token IS NULL AND refresh_token IS NULL AND id_token IS NULL AND access_token_expires_at IS NULL AND refresh_token_expires_at IS NULL AND scope IS NULL AND password IS NULL)
) STRICT;
--> statement-breakpoint
DROP TABLE `provider_identity`;--> statement-breakpoint
ALTER TABLE `__new_provider_identity` RENAME TO `provider_identity`;--> statement-breakpoint
CREATE INDEX `provider_identity_by_account` ON `provider_identity` (`account_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `provider_identity_provider_user` ON `provider_identity` (`provider`,`provider_user_id`);--> statement-breakpoint
CREATE TABLE `__new_developer_account` (
	`account_id` integer PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer NOT NULL,
	`image` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`deleted_at` text,
	CONSTRAINT "developer_account_email" CHECK(email = lower(email) AND email LIKE '%_@_%'),
	CONSTRAINT "developer_account_email_verified" CHECK(email_verified = 1),
	CONSTRAINT "developer_account_image" CHECK(image IS NULL)
) STRICT;
--> statement-breakpoint
DROP TABLE `developer_account`;--> statement-breakpoint
ALTER TABLE `__new_developer_account` RENAME TO `developer_account`;--> statement-breakpoint
CREATE UNIQUE INDEX `developer_account_email_unique` ON `developer_account` (`email`);