-- Generated by drizzle-kit from src/db/app/schema.ts (#240): the reader-report
-- tables move off the dictionary database onto the app database (ADR 0018),
-- then edited by hand so each keeps the exact shape src/db/schema.sql gave it
-- (test/appSchema.test.ts holds it there):
--   * every table is STRICT, which Drizzle cannot declare;
--   * a single-column PRIMARY KEY carries no NOT NULL, as before.
-- Reports filed into the dictionary database before this are not carried over.
-- drizzle-kit's snapshot in ./meta still records what it generated.
CREATE TABLE `reader_report` (
	`report_id` integer PRIMARY KEY,
	`release_id` text NOT NULL,
	`word` text NOT NULL,
	`record_id` integer,
	`choice` text NOT NULL,
	`details` text NOT NULL,
	`visitor_hash` text NOT NULL,
	`received_at` text NOT NULL,
	CONSTRAINT "reader_report_choice" CHECK(choice IN ('meaning', 'example', 'form', 'synonym', 'other')),
	CONSTRAINT "reader_report_details" CHECK(length(details) BETWEEN 1 AND 2000)
) STRICT;
--> statement-breakpoint
CREATE INDEX `reader_report_by_visitor` ON `reader_report` (`visitor_hash`,`received_at`);--> statement-breakpoint
CREATE TABLE `report_opening` (
	`token` text PRIMARY KEY,
	`opened_at` text NOT NULL
) STRICT;
