-- Generated by drizzle-kit from src/db/app/schema.ts (#260): the Stripe
-- plugin's `subscription` table and `developer_account.stripe_customer_id`
-- (`@better-auth/stripe` 1.7.6), and Lexema's own `enterprise_plan`. Then
-- edited by hand: every table it creates is STRICT, which Drizzle cannot
-- declare. drizzle-kit's snapshot in ./meta still records what it generated.
CREATE TABLE `enterprise_plan` (
	`enterprise_plan_id` integer PRIMARY KEY NOT NULL,
	`account_id` integer NOT NULL,
	`calls_per_period` integer NOT NULL,
	`calls_per_minute` integer NOT NULL,
	`period_start` text NOT NULL,
	`period_end` text NOT NULL,
	`ended_at` text,
	FOREIGN KEY (`account_id`) REFERENCES `developer_account`(`account_id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "enterprise_plan_calls_per_period" CHECK(calls_per_period > 0),
	CONSTRAINT "enterprise_plan_calls_per_minute" CHECK(calls_per_minute > 0),
	CONSTRAINT "enterprise_plan_period" CHECK(period_start < period_end)
) STRICT;
--> statement-breakpoint
CREATE UNIQUE INDEX `enterprise_plan_account_id_unique` ON `enterprise_plan` (`account_id`);--> statement-breakpoint
CREATE TABLE `subscription` (
	`subscription_id` integer PRIMARY KEY NOT NULL,
	`plan` text NOT NULL,
	`reference_id` text NOT NULL,
	`stripe_customer_id` text,
	`stripe_subscription_id` text,
	`status` text DEFAULT 'incomplete' NOT NULL,
	`period_start` text,
	`period_end` text,
	`trial_start` text,
	`trial_end` text,
	`cancel_at_period_end` integer DEFAULT false NOT NULL,
	`cancel_at` text,
	`canceled_at` text,
	`ended_at` text,
	`seats` integer,
	`billing_interval` text,
	`stripe_schedule_id` text,
	CONSTRAINT "subscription_plan" CHECK(plan IN ('starter', 'pro')),
	CONSTRAINT "subscription_status" CHECK(status IN ('incomplete', 'incomplete_expired', 'trialing', 'active', 'past_due', 'canceled', 'unpaid', 'paused')),
	CONSTRAINT "subscription_reference_id" CHECK(reference_id GLOB '[1-9]*' AND reference_id NOT GLOB '*[^0-9]*'),
	CONSTRAINT "subscription_period" CHECK(period_start IS NULL OR period_end IS NULL OR period_start < period_end),
	CONSTRAINT "subscription_serving_period" CHECK(status NOT IN ('active', 'trialing', 'past_due') OR (period_start IS NOT NULL AND period_end IS NOT NULL)),
	CONSTRAINT "subscription_seats" CHECK(seats IS NULL OR seats > 0)
) STRICT;
--> statement-breakpoint
CREATE UNIQUE INDEX `subscription_stripe_subscription_id_unique` ON `subscription` (`stripe_subscription_id`);--> statement-breakpoint
CREATE INDEX `subscription_by_reference` ON `subscription` (`reference_id`);--> statement-breakpoint
ALTER TABLE `developer_account` ADD `stripe_customer_id` text;--> statement-breakpoint
CREATE UNIQUE INDEX `developer_account_stripe_customer_id_unique` ON `developer_account` (`stripe_customer_id`);