-- Generated by drizzle-kit from src/db/app/schema.ts (#215): `plan_notice`,
-- what each account was last emailed about each Stripe subscription. Then
-- edited by hand: the table is STRICT, which Drizzle cannot declare.
-- drizzle-kit's snapshot in ./meta still records what it generated.
CREATE TABLE `plan_notice` (
	`stripe_subscription_id` text PRIMARY KEY NOT NULL,
	`account_id` integer NOT NULL,
	`plan` text NOT NULL,
	`state` text NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `developer_account`(`account_id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "plan_notice_plan" CHECK(plan IN ('starter', 'pro')),
	CONSTRAINT "plan_notice_state" CHECK(state IN ('active', 'past-due', 'cancelling', 'ended'))
) STRICT;
