-- Generated by drizzle-kit from src/db/app/schema.ts (#12): a reader report
-- keeps the source line of the reading it names, and a person's answer. Then
-- edited by hand:
--   * the table is STRICT, which Drizzle cannot declare, and its single-column
--     PRIMARY KEY carries no NOT NULL, as 0002 made it;
--   * the copy reads only the columns the old table has, so a report already
--     stored keeps its record_id with no line and waits for an answer;
--   * no `PRAGMA foreign_keys` around the rebuild: no foreign key names this
--     table.
-- drizzle-kit's snapshot in ./meta still records what it generated.
CREATE TABLE `__new_reader_report` (
	`report_id` integer PRIMARY KEY,
	`release_id` text NOT NULL,
	`word` text NOT NULL,
	`record_id` integer,
	`line_no` integer,
	`line_sha256` text,
	`choice` text NOT NULL,
	`details` text NOT NULL,
	`visitor_hash` text NOT NULL,
	`received_at` text NOT NULL,
	`outcome` text,
	`reviewed_at` text,
	`reviewed_by` text,
	CONSTRAINT "reader_report_choice" CHECK(choice IN ('meaning', 'example', 'form', 'synonym', 'other')),
	CONSTRAINT "reader_report_details" CHECK(length(details) BETWEEN 1 AND 2000),
	CONSTRAINT "reader_report_line" CHECK((line_no IS NULL AND line_sha256 IS NULL) OR (line_no IS NOT NULL AND line_sha256 IS NOT NULL AND record_id IS NOT NULL AND line_no > 0 AND length(line_sha256) = 64)),
	CONSTRAINT "reader_report_review" CHECK((outcome IS NULL AND reviewed_at IS NULL AND reviewed_by IS NULL) OR (outcome IS NOT NULL AND reviewed_at IS NOT NULL AND reviewed_by IS NOT NULL AND length(outcome) BETWEEN 1 AND 2000 AND length(reviewed_by) > 0))
) STRICT;
--> statement-breakpoint
INSERT INTO `__new_reader_report`("report_id", "release_id", "word", "record_id", "choice", "details", "visitor_hash", "received_at") SELECT "report_id", "release_id", "word", "record_id", "choice", "details", "visitor_hash", "received_at" FROM `reader_report`;--> statement-breakpoint
DROP TABLE `reader_report`;--> statement-breakpoint
ALTER TABLE `__new_reader_report` RENAME TO `reader_report`;--> statement-breakpoint
CREATE INDEX `reader_report_by_visitor` ON `reader_report` (`visitor_hash`,`received_at`);
