-- Generated by drizzle-kit from src/db/app/schema.ts (#570): a report keeps
-- the reader's own data only while it serves. `visitor_hash` may be NULL, as
-- it is from one hour after the report arrives, and is 64 characters when
-- present; `details` is held while the report waits and NULL once it is
-- answered. Then edited by hand, as 0005 to 0007 were:
--   * the table is STRICT, which Drizzle cannot declare, and its single-column
--     PRIMARY KEY carries no NOT NULL, as 0002 made it;
--   * no `PRAGMA foreign_keys` around the rebuild: no foreign key names this
--     table;
--   * a report already answered is copied with its note erased, since the new
--     CHECK refuses an answered report that keeps one. Every other report is
--     copied as it stands.
-- drizzle-kit's snapshot in ./meta still records what it generated.
CREATE TABLE `__new_reader_report` (
	`report_id` integer PRIMARY KEY,
	`release_id` text NOT NULL,
	`word` text NOT NULL,
	`record_id` integer,
	`line_no` integer,
	`line_sha256` text,
	`choice` text NOT NULL,
	`details` text,
	`visitor_hash` text,
	`received_at` text NOT NULL,
	`outcome` text,
	`reviewed_at` text,
	`reviewed_by` text,
	CONSTRAINT "reader_report_choice" CHECK(choice IN ('meaning', 'example', 'form', 'synonym', 'other', 'missing')),
	CONSTRAINT "reader_report_missing" CHECK(choice <> 'missing' OR record_id IS NULL),
	CONSTRAINT "reader_report_details" CHECK((outcome IS NULL AND details IS NOT NULL AND length(details) <= 2000 AND (choice = 'missing' OR length(details) >= 1)) OR (outcome IS NOT NULL AND details IS NULL)),
	CONSTRAINT "reader_report_visitor_hash" CHECK(visitor_hash IS NULL OR length(visitor_hash) = 64),
	CONSTRAINT "reader_report_line" CHECK((line_no IS NULL AND line_sha256 IS NULL) OR (line_no IS NOT NULL AND line_sha256 IS NOT NULL AND record_id IS NOT NULL AND line_no > 0 AND length(line_sha256) = 64)),
	CONSTRAINT "reader_report_review" CHECK((outcome IS NULL AND reviewed_at IS NULL AND reviewed_by IS NULL) OR (outcome IS NOT NULL AND reviewed_at IS NOT NULL AND reviewed_by IS NOT NULL AND length(outcome) BETWEEN 1 AND 2000 AND length(reviewed_by) > 0))
) STRICT;
--> statement-breakpoint
INSERT INTO `__new_reader_report`("report_id", "release_id", "word", "record_id", "line_no", "line_sha256", "choice", "details", "visitor_hash", "received_at", "outcome", "reviewed_at", "reviewed_by") SELECT "report_id", "release_id", "word", "record_id", "line_no", "line_sha256", "choice", CASE WHEN "outcome" IS NULL THEN "details" END, "visitor_hash", "received_at", "outcome", "reviewed_at", "reviewed_by" FROM `reader_report`;--> statement-breakpoint
DROP TABLE `reader_report`;--> statement-breakpoint
ALTER TABLE `__new_reader_report` RENAME TO `reader_report`;--> statement-breakpoint
CREATE INDEX `reader_report_by_visitor` ON `reader_report` (`visitor_hash`,`received_at`);
