-- Generated by drizzle-kit from src/db/app/schema.ts (#573): an account's
-- suspension, when it began and why, and the Radar items a suspension added.
-- Then edited by hand:
--   * the new table is STRICT, which Drizzle cannot declare;
--   * drizzle-kit rebuilt `developer_account` to add its new CHECK. Most app
--     tables name that table in a foreign key, so the two columns are added in
--     place instead, the CHECK on the second of them. SQLite tests it against
--     every row already stored, and a column CHECK enforces what a table CHECK
--     does (test/appSchema.test.ts compares them as one).
-- drizzle-kit's snapshot in ./meta still records what it generated.
CREATE TABLE `suspension_card_block` (
	`account_id` integer NOT NULL,
	`value_list_item_id` text NOT NULL,
	`card_fingerprint` text NOT NULL,
	PRIMARY KEY(`account_id`, `value_list_item_id`),
	FOREIGN KEY (`account_id`) REFERENCES `developer_account`(`account_id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "suspension_card_block_item" CHECK(value_list_item_id GLOB 'rsli_*'),
	CONSTRAINT "suspension_card_block_fingerprint" CHECK(length(card_fingerprint) > 0)
) STRICT;
--> statement-breakpoint
CREATE INDEX `suspension_card_block_by_item` ON `suspension_card_block` (`value_list_item_id`);--> statement-breakpoint
ALTER TABLE `developer_account` ADD `suspended_at` text;--> statement-breakpoint
ALTER TABLE `developer_account` ADD `suspension_reason` text CONSTRAINT "developer_account_suspension" CHECK((suspended_at IS NULL AND suspension_reason IS NULL) OR (suspended_at IS NOT NULL AND suspension_reason IS NOT NULL AND length(suspension_reason) BETWEEN 1 AND 500 AND suspension_reason = trim(suspension_reason)));
