// Turn an imported SQLite database into SQL that `wrangler d1 execute --file`
// can load.
//
// This exists because local D1 is only reachable through wrangler's CLI, which
// takes SQL text — there is no supported way to hand miniflare a SQLite file we
// built ourselves. For development that is fine: a few thousand records is
// plenty to build a page against. Loading a full release into real D1 is a
// different problem and belongs to #18.

import { createWriteStream } from "node:fs";
import { readFile } from "node:fs/promises";
import { DatabaseSync } from "node:sqlite";

/**
 * Parent before child: every table here is written after the tables its foreign
 * keys point at, so the dump loads with `PRAGMA foreign_keys` on.
 */
const TABLES = [
  "source_release",
  "release_table_rows",
  "source_record",
  "source_record_json",
  "lookup_form",
  "form_of_edge",
  "sense",
  "sense_gloss",
  "sense_label",
  "grammar_claim",
  "claim_review",
] as const;

// `grammar_value` is deliberately absent from TABLES: schema.sql seeds it with
// its own INSERT, so dumping the rows too would collide on the primary key.
const SEEDED_BY_SCHEMA = new Set(["grammar_value"]);

/**
 * Refuse a database holding a table this dump does not know about.
 *
 * TABLES is hand-ordered, because a dump has to write a parent before its
 * children and SQLite will not tell you that order. A hand-kept list silently
 * stops covering the schema the moment a table is added — which is exactly how
 * the importer's own `release_table_rows` was left out of every dump — so the
 * list is checked against the database it is about to read.
 */
function assertCoversEveryTable(db: DatabaseSync): void {
  const present = (
    db.prepare(
      `SELECT name FROM sqlite_master
        WHERE type = 'table' AND name NOT LIKE 'sqlite_%'`,
    ).all() as { name: string }[]
  ).map((row) => row.name);

  const covered = new Set<string>(TABLES);
  const missed = present.filter((name) => !covered.has(name) && !SEEDED_BY_SCHEMA.has(name));
  if (missed.length > 0) {
    throw new Error(
      `exportSql does not dump ${missed.join(", ")}; add each to TABLES after the ` +
        `tables its foreign keys point at`,
    );
  }
}

function literal(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  if (typeof value === "bigint") return String(value);
  // Escape by doubling the quote, which is the only escape SQLite string
  // literals have. JSON payloads arrive full of quotes and backslashes and must
  // survive the round trip byte for byte.
  return `'${String(value).replace(/'/g, "''")}'`;
}

export interface ExportOptions {
  database: string;
  schema: string;
  output: string;
  /**
   * Byte budget per INSERT statement.
   *
   * Batching by row count does not work here: a `source_record_json` row is
   * several kilobytes while a `lookup_form` row is a few dozen bytes, so any
   * fixed row count is either wasteful or over the limit. SQLite raises
   * SQLITE_TOOBIG on an oversized statement, and wrangler surfaces it with no
   * hint as to which table caused it.
   *
   * 64 KiB was found by bisection against `wrangler d1 execute --local`: a
   * ~119 KB statement is refused, ~60 KB is accepted. The limit is not
   * documented, so this leaves real headroom under the smallest value observed
   * to fail rather than sitting just below it.
   */
  maxStatementBytes?: number;
}

export async function exportSql(options: ExportOptions): Promise<{ statements: number }> {
  const maxStatementBytes = options.maxStatementBytes ?? 64 * 1024;
  const schemaSql = await readFile(options.schema, "utf8");
  const db = new DatabaseSync(options.database, { readOnly: true });
  const out = createWriteStream(options.output, { encoding: "utf8" });

  // The output's error listener is attached before the first byte, not during
  // cleanup: a disk that fills on statement one must fail this run rather than
  // leave a truncated dump behind an unheard 'error' event — and a write that
  // is waiting for 'drain' on a stream that just failed never gets one, so the
  // wait is raced against the failure.
  const closed = new Promise<void>((resolve, reject) => {
    out.once("error", reject);
    out.once("close", resolve);
  });
  // Keeps an early failure from being an unhandled rejection before the run
  // reaches the `await closed` that rethrows it.
  void closed.catch(() => {});

  const write = (chunk: string): Promise<void> =>
    out.write(chunk)
      ? Promise.resolve()
      : Promise.race([new Promise<void>((resolve) => out.once("drain", () => resolve())), closed]);

  let statements = 0;
  try {
    assertCoversEveryTable(db);
    await write("-- Generated by src/import/exportSql.ts. Do not edit.\n");
    // schema.sql goes in whole, including its grammar_value seed.
    await write(schemaSql);
    await write("\n\n");

    for (const table of TABLES) {
      const columns = (
        db.prepare(`PRAGMA table_info(${table})`).all() as { name: string }[]
      ).map((column) => column.name);
      const rows = db.prepare(`SELECT * FROM ${table}`).all() as Record<string, unknown>[];
      if (rows.length === 0) continue;

      await write(`-- ${table}: ${rows.length} row(s)\n`);
      const prefix = `INSERT INTO ${table} (${columns.join(",")}) VALUES\n  `;
      let batch: string[] = [];
      let bytes = 0;

      const flush = async (): Promise<void> => {
        if (batch.length === 0) return;
        await write(`${prefix}${batch.join(",\n  ")};\n`);
        statements += 1;
        batch = [];
        bytes = 0;
      };

      for (const row of rows) {
        const tuple = `(${columns.map((column) => literal(row[column])).join(",")})`;
        // A single row over budget still has to go out on its own; splitting a
        // row is not an option, so it is emitted and the limit is exceeded
        // knowingly rather than silently truncated.
        if (bytes > 0 && bytes + tuple.length > maxStatementBytes) await flush();
        batch.push(tuple);
        bytes += tuple.length + 4;
      }
      await flush();
      await write("\n");
    }
  } finally {
    db.close();
    out.end();
    await closed;
  }

  return { statements };
}
