// `normalize:source-text` as one SQL file (#455): every source text rule's
// update (ADR 0019), planned in the order the seed applies them and run in one
// step, like an apply (src/update/apply.ts). A later rule reads the glosses an
// earlier one rewrites from the plan, not the database, so the file does what
// running the rules one after another did.

import { GLOSS_GRAMMAR_STAMP_RULE } from "../italian/glossGrammarStamp.js";
import { SOURCE_TEXT_RULES } from "../italian/sourceTextNormalization.js";
import type { MasterReader } from "../update/master.js";
import { PlanCounts, type CountedTable, type TableRows } from "../update/planCounts.js";
import { type GlossStampReport, planGlossStamps } from "./glossStampUpdate.js";
import { type HeadwordLeadReport, planHeadwordLeads } from "./headwordLeadUpdate.js";
import { type FormNormalizationReport, planPlaceholderForms } from "./normalizeForms.js";
import { type GlossNormalizationReport, planPersonOrdinals } from "./normalizeGlosses.js";
import { PlannedGlosses, type RulePlan } from "./sourceTextUpdate.js";

/**
 * The rules `normalize:source-text` applies, in the order it applies them:
 * the seed takes a headword lead off before it normalizes what is left.
 */
export const SOURCE_TEXT_UPDATE_RULES = [
  SOURCE_TEXT_RULES.headwordLeadGloss,
  SOURCE_TEXT_RULES.personOrdinalGloss,
  SOURCE_TEXT_RULES.pluralPlaceholderForm,
  GLOSS_GRAMMAR_STAMP_RULE,
] as const;

export type SourceTextUpdateRule = (typeof SOURCE_TEXT_UPDATE_RULES)[number];

/** What each rule found, as its own update reports it. */
export interface SourceTextReports {
  readonly headwordLeads: HeadwordLeadReport;
  readonly glosses: GlossNormalizationReport;
  readonly forms: FormNormalizationReport;
  readonly glossStamps: GlossStampReport;
}

/** The whole update, ready to run. */
export interface SourceTextPlan {
  readonly reports: SourceTextReports;
  /** Statements in the file; 0 on a database already normalized. */
  readonly statements: number;
  readonly counts: PlanCounts;
  /** Empty when there is nothing to change. */
  readonly sql: string;
}

function added(into: Partial<Record<CountedTable, number>>, rows: TableRows): void {
  for (const [table, n] of Object.entries(rows) as [CountedTable, number][]) into[table] = (into[table] ?? 0) + n;
}

/** Plan every rule into one file. It reads the database; it writes nothing. */
export function planSourceText(db: MasterReader): SourceTextPlan {
  const glosses = new PlannedGlosses();
  const headwordLeads = planHeadwordLeads(db, glosses);
  const personOrdinals = planPersonOrdinals(db, glosses);
  const forms = planPlaceholderForms(db, glosses);
  const glossStamps = planGlossStamps(db, glosses);
  const plans: RulePlan<unknown>[] = [headwordLeads, personOrdinals, forms, glossStamps];

  const glossRows = glosses.rows();
  const written: Partial<Record<CountedTable, number>> = { sense_gloss: glossRows.written };
  const deleted: Partial<Record<CountedTable, number>> = { sense_gloss: glossRows.deleted };
  for (const plan of plans) {
    added(written, plan.written);
    added(deleted, plan.deleted);
  }
  const records = new Set([...glosses.records(), ...plans.flatMap((plan) => plan.records)]);
  const statements = plans.flatMap((plan) => plan.statements);
  return {
    reports: { headwordLeads: headwordLeads.report, glosses: personOrdinals.report, forms: forms.report, glossStamps: glossStamps.report },
    statements: statements.length,
    counts: new PlanCounts({ added: 0, changed: records.size, removed: 0 }, written, deleted),
    sql: statements.length === 0
      ? ""
      : [`-- Generated by src/import/normalizeSourceText.ts: ${SOURCE_TEXT_UPDATE_RULES.join(", ")}.`, ...statements, ""].join("\n"),
  };
}

/**
 * Plan every rule, run the file in one step through `applyFile`, then read the
 * database back. Throws when anything is still pending afterwards.
 */
export async function normalizeSourceText(db: MasterReader, applyFile: (sql: string) => Promise<void> | void): Promise<SourceTextPlan> {
  const plan = planSourceText(db);
  if (plan.sql !== "") await applyFile(plan.sql);
  const after = planSourceText(db);
  if (after.statements > 0) throw new Error(`${after.statements} source text change(s) still pending after the update`);
  return plan;
}
