// One real word for each shape the #707 census found
// (reports/2026-10-07-word-page-shapes.json), keyed by the shape as the census
// writes it, in the census's order. wordPageRules.test.tsx checks that each
// word's page has its shape and keeps every built rule. The words are
// it-0c432803's: their lines are in fixtures/dev-seed.jsonl, or in
// fixtures/no-base-record.jsonl when one of their form_of edges names a word
// with no record (docs/DEV_SEED.md). `skirmishes`, the word of `no page
// (not-found)`, has no lines here: the release hides its one record as
// another language's (form-of-foreign-lemma/v1), so its search finds nothing
// there either.

export const SHAPE_WORDS: Readonly<Record<string, string>> = {
  "verb-form · 1 reading · no links": "vada",
  "form-of verb · 1 reading · no links": "zurlò",
  "own noun · 1 reading · no links": "casa",
  "own other · 1 reading · no links": "Russia",
  "form-of noun · 1 reading · no links": "attrice",
  "form-of adjective · 1 reading · no links": "costruttrici",
  "own adjective · 1 reading · no links": "gravido",
  "own verb · 1 reading · no links": "finire",
  "own adjective · own noun · 2 readings, 1 word · no links": "grande",
  "form-of adjective · verb-form · 2 readings, 2+ words · links": "andati",
  "own adjective · verb-form · 2 readings, 2+ words · links": "litigante",
  "own noun · verb-form · 2 readings, 2+ words · links": "studente",
  "lone-bare · 1 reading · no links": "sbucciapatate",
  "form-of noun · verb-form · 2 readings, 2+ words · links": "parti",
  "own adjective · own noun · verb-form · 3+ readings · links": "fatto",
  "form-of adjective · own noun · 2 readings, 2+ words · links": "massimo",
  "verb-form · 2 readings, 2+ words · links": "salivate",
  "a spelling variant's record · own noun · own other · 2 readings, 2+ words · links": "abaco",
  "a spelling variant's record · own noun · 2 readings, 2+ words · links": "Betula",
  "own verb · 2 readings, 1 word · no links": "volgere",
  "form-of verb · own adjective · 2 readings, 2+ words · links": "dinoccolato",
  "form-of adjective · form-of verb · 2 readings, 2+ words · links": "duellanti",
  "form-of verb · own noun · 2 readings, 2+ words · links": "assegno",
  "form-of adjective · form-of noun · 2 readings, 2+ words · links": "massime",
  "own adjective · own noun · 3+ readings · links": "inglese",
  "form-of verb · own adjective · verb-form · 3+ readings · links": "barricato",
  "form-of adjective · own noun · verb-form · 3+ readings · links": "andata",
  "form-of verb · verb-form · 2 readings, 2+ words · links": "informicolito",
  "a spelling variant's record · own adjective · own noun · own other · 3+ readings · links": "Estero",
  "own noun form record · 1 reading · no links": "gommiste",
  "own adjective · verb-form · 3+ readings · links": "imposto",
  "form-of noun · own noun · 2 readings, 2+ words · links": "Pizie",
  "own adjective form record · 1 reading · no links": "vuote",
  "a spelling variant's record · own adjective · own other · 2 readings, 2+ words · links": "Gaio",
  "own other · verb-form · 2 readings, 2+ words · links": "sarà",
  "own other · 2 readings, 1 word · no links": "le",
  "form-of adjective · form-of noun · verb-form · 3+ readings · links": "andate",
  "a spelling variant's record · own other · verb-form · 2 readings, 2+ words · links": "grazio",
  "own noun · 2 readings, 1 word · no links": "eurogruppo",
  "form-of noun · form-of verb · 2 readings, 2+ words · links": "assegni",
  "a spelling variant's record · own noun · own other · verb-form · 3+ readings · links": "Tiro",
  "own noun · own other · 2 readings, 1 word · no links": "al di là",
  "form-of adjective · own other · 2 readings, 2+ words · links": "Beata",
  "own verb form record · verb-form · 2 readings, 2+ words · links": "logorò",
  "a spelling variant's record · own adjective · own noun · 3+ readings · links": "Ternano",
  "a spelling variant's record · own noun · own other · 3+ readings · links": "Ortolano",
  "form-of verb · own adjective · own noun · 3+ readings · links": "duellante",
  "own noun · verb-form · 3+ readings · links": "saliva",
  "a spelling variant's record · own other · 2 readings, 2+ words · links": "AC",
  "a spelling variant's record · form-of adjective · own other · 2 readings, 2+ words · links": "beata",
  "a spelling variant's record · own adjective · own noun · own other · verb-form · 3+ readings · links": "Fermo",
  "a spelling variant's record · own adjective · own other · verb-form · 3+ readings · links": "Chino",
  "own adjective · own noun · own other · 3+ readings · links": "altro",
  "form-of adjective · verb-form · 3+ readings · links": "volti",
  "own adjective · own other · 2 readings, 1 word · no links": "sottovento",
  "form-of adjective · own verb form record · 2 readings, 2+ words · links": "logorata",
  "a verb block and a noun or adjective block about one word · form-of adjective · verb-form · 2 readings, 1 word · no links": "presiedute",
  "own adjective form record · verb-form · 2 readings, 2+ words · links": "affiatata",
  "form-of verb · own other · 2 readings, 2+ words · links": "ci sono",
  "a spelling variant's record · form-of noun · own noun · 2 readings, 2+ words · links": "pizie",
  "a spelling variant's record · form-of verb · own other · 2 readings, 2+ words · links": "gemmo",
  "own adjective · own verb · 2 readings, 1 word · no links": "salivare",
  "own adjective · own verb form record · verb-form · 3+ readings · links": "fu",
  "a spelling variant's record · own adjective · own noun · 2 readings, 2+ words · links": "Scandinaviano",
  "grid-form · 1 reading · no links": "gravida",
  "own noun · own verb form record · verb-form · 3+ readings · links": "domicilio",
  "own verb form record · 1 reading · no links": "abbattette",
  "form-of adjective · form-of noun · two blocks about one word · 2 readings, 1 word · no links": "calabra",
  "a spelling variant's record · form-of adjective · own noun · own other · 3+ readings · links": "Massima",
  "form-of noun · verb-form · 3+ readings · links": "Stati",
  "own noun · own verb · 2 readings, 1 word · no links": "andare",
  "form-of noun · own other · 2 readings, 2+ words · links": "Sante",
  "a spelling variant's record · form-of adjective · own noun · 2 readings, 2+ words · links": "farinose",
  "a spelling variant's record · own noun · verb-form · 3+ readings · links": "stato",
  "own noun · own other · verb-form · 3+ readings · links": "fa",
  "a spelling variant's record · form-of adjective · own other · verb-form · 3+ readings · links": "veneranda",
  "own adjective · own noun · own verb · 3+ readings · links": "scalare",
  "form-of adjective · own noun form record · 2 readings, 2+ words · links": "aerei",
  "form-of adjective · own other · verb-form · 3+ readings · links": "Veneranda",
  "form-of other · 1 reading · no links": "Russie",
  "own adjective · 2 readings, 1 word · no links": "ventenne",
  "own adjective form record · own noun · 2 readings, 1 word · no links": "santa",
  "a spelling variant's record · form-of adjective · own noun · 3+ readings · links": "Punica",
  "form-of noun · 2 readings, 2+ words · links": "greci",
  "form-of verb · 2 readings, 2+ words · links": "rinsavire",
  "form-of adjective · form-of verb · own noun · 3+ readings · links": "decima",
  "own noun · own other · 3+ readings · links": "via",
  "own noun · own verb · 3+ readings · links": "essere",
  "a spelling variant's record · form-of adjective · own noun · own other · verb-form · 3+ readings · links": "china",
  "a spelling variant's record · form-of noun · own other · 2 readings, 2+ words · links": "sante",
  "a spelling variant's record · own noun · 3+ readings · links": "MP3",
  "own adjective · own noun · own verb form record · verb-form · 3+ readings · links": "sciamannato",
  "a spelling variant's record · own adjective · own noun · verb-form · 3+ readings · links": "Foggiano",
  "a spelling variant's record · own other · 3+ readings · links": "EI",
  "bare · 2 readings, 1 word · no links": "innanzi",
  "form-of 2+ base words · form-of noun · 1 reading · no links": "geni",
  "form-of noun · own noun · verb-form · 3+ readings · links": "sale",
  "own adjective · own noun · own other · verb-form · 3+ readings · links": "6",
  "own adjective · own verb · verb-form · 3+ readings · links": "socchiuso",
  "own adjective form record · own noun form record · 2 readings, 1 word · no links": "tanghere",
  "own noun · own noun form record · 2 readings, 1 word · no links": "faccendone",
  "own noun · own verb form record · 2 readings, 1 word · no links": "fuoriuscito",
  "own verb · verb-form · 2 readings, 2+ words · links": "dovremmo",
  "a spelling variant's record · own noun · 1 reading · no links": "Gennaro",
  "form-of noun · own adjective · verb-form · 3+ readings · links": "morse",
  "own noun · own verb · verb-form · 3+ readings · links": "laureando",
  "a spelling variant's record · form-of noun · own noun · 3+ readings · links": "Primati",
  "a spelling variant's record · own other · 1 reading · no links": "all’incirca",
  "another word's record · grid-form · own adjective form record · 2 readings, 2+ words · links": "aerea",
  "form-of noun · own adjective · 2 readings, 2+ words · links": "glutei",
  "form-of noun · own verb form record · verb-form · 3+ readings · links": "impieghi",
  "own adjective · own other · verb-form · 3+ readings · links": "aggruppato",
  "own noun form record · verb-form · 2 readings, 2+ words · links": "fiati",
  "a spelling variant's record · form-of noun · own noun · own other · 3+ readings · links": "primina",
  "a spelling variant's record · own adjective · own noun · 2 readings, 1 word · no links": "Asfodelo",
  "form-of 2+ base words · form-of noun · verb-form · 2 readings, 2+ words · links": "auguri",
  "form-of adjective · own noun form record · verb-form · 3+ readings · links": "compartecipi",
  "form-of adjective · own verb form record · verb-form · 3+ readings · links": "logora",
  "form-of noun · own noun · 2 readings, 1 word · no links": "rozzone",
  "no page (not-found)": "skirmishes",
  "a spelling variant's record · own adjective form record · own other · 2 readings, 2+ words · links": "alessandrina",
  "another word's record · own other · 1 reading · no links": "Daria",
  "form-of 2+ base words · form-of verb · 1 reading · no links": "instillare",
  "form-of adjective · form-of noun · two blocks about one word · verb-form · 3+ readings · links": "coartata",
  "own adjective · own other · 3+ readings · links": "alquanto",
  "own other · 3+ readings · links": "fuori",
  "a spelling variant's record · form-of adjective · form-of noun · own other · 3+ readings · links": "ortolana",
  "a spelling variant's record · own adjective · 1 reading · no links": "Italo",
  "a spelling variant's record · own noun · verb-form · 2 readings, 2+ words · links": "tifa",
  "a spelling variant's record · own other · verb-form · 3+ readings · links": "sta",
  "form-of adjective · form-of noun · own noun · 3+ readings · links": "basilica",
  "form-of adjective · form-of other · two blocks about one word · 2 readings, 1 word · no links": "altri",
  "form-of adjective · own noun · own verb form record · 3+ readings · links": "pettinata",
  "form-of verb · own adjective · own noun · verb-form · 3+ readings · links": "rimbambito",
  "own adjective · own noun · own verb form record · 3+ readings · links": "stampante",
  "own noun · 3+ readings · links": "poma",
  "a spelling variant's record · form-of noun · own other · verb-form · 3+ readings · links": "bari",
  "a spelling variant's record · form-of verb · own noun · 3+ readings · links": "Sdentati",
  "a spelling variant's record · form-of verb · own noun · own other · 3+ readings · links": "rubino",
  "a spelling variant's record · own adjective · 2 readings, 2+ words · links": "neodevoniano",
  "a spelling variant's record · own adjective · own noun · own other · own verb · verb-form · 3+ readings · links": "argentino",
  "a verb block and a noun or adjective block about one word · form-of adjective · verb-form · 3+ readings · links": "laureati",
  "form-of adjective · own verb · 2 readings, 2+ words · links": "leggere",
  "form-of noun · own adjective · own noun · 3+ readings · links": "messinese",
  "form-of noun · own other · verb-form · 3+ readings · links": "Bari",
  "form-of verb · own adjective form record · 2 readings, 2+ words · links": "inframmettente",
  "own adjective · own verb form record · 2 readings, 1 word · no links": "pascente",
  "own adjective form record · own noun · verb-form · 3+ readings · links": "pensionata",
  "own adjective form record · own noun form record · verb-form · 3+ readings · links": "vigili",
  "own other · verb-form · 3+ readings · links": "STA",
  "a spelling variant's record · form-of noun · own other · 3+ readings · links": "PA",
  "form-of adjective · form-of noun · 3+ readings · links": "greca",
  "form-of adjective · form-of noun · form-of verb · 3+ readings · links": "scapigliate",
  "form-of adjective · form-of noun · own other · 3+ readings · links": "Ortolana",
  "form-of adjective · form-of verb · verb-form · 3+ readings · links": "involta",
  "form-of adjective · own adjective · own noun · 3+ readings · links": "maggiore",
  "form-of noun · own adjective form record · 2 readings, 2+ words · links": "orbi",
  "form-of noun · own verb · 2 readings, 2+ words · links": "massare",
  "form-of verb · own noun · verb-form · 3+ readings · links": "slancio",
  "own verb · 3+ readings · links": "asciugare",
  "verb-form · 3+ readings · links": "acclimata",
  "a spelling variant's record · a verb block and a noun or adjective block about one word · form-of adjective · form-of verb · own other · 3+ readings · links": "Giusta",
  "a spelling variant's record · bare · 2 readings, 2+ words · links": "SLA",
  "a spelling variant's record · form-of adjective · form-of verb · own noun · own other · 3+ readings · links": "Pellegrina",
  "a spelling variant's record · form-of adjective · form-of verb · own other · 3+ readings · links": "lisa",
  "a spelling variant's record · form-of adjective · own adjective · own noun · own other · verb-form · 3+ readings · links": "Rosa",
  "a spelling variant's record · form-of adjective · own noun · own other · own verb form record · verb-form · 3+ readings · links": "Ferma",
  "a spelling variant's record · form-of adjective · own noun · verb-form · 3+ readings · links": "umiliati",
  "a spelling variant's record · form-of noun · own adjective form record · own other · 3+ readings · links": "Slava",
  "a spelling variant's record · form-of noun · own noun · own other · verb-form · 3+ readings · links": "Uccelli",
  "a spelling variant's record · form-of verb · own adjective · own other · 3+ readings · links": "Sincero",
  "a spelling variant's record · form-of verb · own adjective · own other · verb-form · 3+ readings · links": "Incoronato",
  "a spelling variant's record · form-of verb · own noun · 2 readings, 2+ words · links": "vulgata",
  "a spelling variant's record · own adjective · own noun · own other · own verb form record · verb-form · 3+ readings · links": "Beato",
  "a spelling variant's record · own adjective · own noun · own verb form record · 3+ readings · links": "Sorbo",
  "a spelling variant's record · own adjective · own other · 3+ readings · links": "Loro",
  "a spelling variant's record · own adjective · own other · own verb form record · verb-form · 3+ readings · links": "Divino",
  "a spelling variant's record · own adjective form record · own noun · own other · 3+ readings · links": "Nana",
  "a spelling variant's record · own adjective form record · own other · verb-form · 3+ readings · links": "Roso",
  "a spelling variant's record · own noun · own other · own verb · verb-form · 3+ readings · links": "Grazia",
  "a spelling variant's record · own noun · own other · own verb form record · verb-form · 3+ readings · links": "Corona",
  "a spelling variant's record · own noun form record · own other · verb-form · 3+ readings · links": "Incoronata",
  "a verb block and a noun or adjective block about one word · form-of adjective · form-of verb · 2 readings, 1 word · no links": "agghiaccianti",
  "a verb block and a noun or adjective block about one word · form-of adjective · own noun · verb-form · 3+ readings · links": "scalata",
  "a verb block and a noun or adjective block about one word · form-of noun · verb-form · 2 readings, 1 word · no links": "badanti",
  "another word's record · grid-form · own adjective form record · 3+ readings · links": "soli",
  "another word's record · own noun form record · 1 reading · no links": "casette",
  "form-of 2+ base words · form-of adjective · form-of noun · form-of verb · 3+ readings · links": "sommosse",
  "form-of 2+ base words · form-of adjective · form-of verb · 2 readings, 2+ words · links": "rimossa",
  "form-of 2+ base words · form-of adjective · form-of verb · own noun · 3+ readings · links": "imposta",
  "form-of 2+ base words · form-of adjective · verb-form · 2 readings, 2+ words · links": "rimpatriate",
  "form-of 2+ base words · form-of noun · form-of verb · 2 readings, 2+ words · links": "lamenti",
  "form-of 2+ base words · form-of noun · verb-form · 3+ readings · links": "picchi",
  "form-of 2+ base words · form-of verb · own adjective · 2 readings, 2+ words · links": "smosso",
  "form-of adjective · form-of noun · own noun · two blocks about one word · 3+ readings · links": "numismatica",
  "form-of adjective · form-of verb · 3+ readings · links": "rinvolta",
  "form-of adjective · form-of verb · own other · 3+ readings · links": "Lisa",
  "form-of adjective · own noun · 3+ readings · links": "chiarificatori",
  "form-of adjective · own noun · own verb · 3+ readings · links": "smentita",
  "form-of noun · own noun · 3+ readings · links": "ballerina",
  "form-of noun · own other · 3+ readings · links": "onde",
  "form-of noun · own verb · verb-form · 3+ readings · links": "domicili",
  "form-of noun · own verb form record · 2 readings, 2+ words · links": "vestiti",
  "form-of verb · own adjective form record · verb-form · 3+ readings · links": "stagnato",
  "own adjective · own noun · own verb · verb-form · 3+ readings · links": "diserbante",
  "own adjective form record · verb-form · 3+ readings · links": "disadorna",
  "a spelling variant's record · a verb block and a noun or adjective block about one word · form-of adjective · own other · verb-form · 3+ readings · links": "addolorata",
  "a spelling variant's record · form-of adjective · own other · 3+ readings · links": "gaia",
  "a spelling variant's record · form-of noun · own noun · verb-form · 3+ readings · links": "numeri",
  "a spelling variant's record · form-of verb · own adjective · 2 readings, 2+ words · links": "vulgato",
  "a spelling variant's record · form-of verb · own other · 3+ readings · links": "vania",
  "a spelling variant's record · own noun · own other · 2 readings, 1 word · no links": "V",
  "a verb block and a noun or adjective block about one word · form-of adjective · own other · verb-form · 3+ readings · links": "Addolorata",
  "another word's record · grid-form · own adjective form record · own noun form record · 3+ readings · links": "amici",
  "another word's record · grid-form · own noun form record · 2 readings, 2+ words · links": "controllori",
  "another word's record · grid-form · own noun form record · 3+ readings · links": "studentesse",
  "form-of 2+ base words · form-of adjective · 1 reading · no links": "esteri",
  "form-of 2+ base words · form-of adjective · form-of noun · 2 readings, 2+ words · links": "predatori",
  "form-of 2+ base words · form-of noun · own noun · 2 readings, 2+ words · links": "pali",
  "form-of 2+ base words · form-of verb · own noun · 2 readings, 2+ words · links": "esercito",
  "form-of adjective · 2 readings, 2+ words · links": "operatori",
  "form-of adjective · form-of noun · own adjective · 3+ readings · links": "estense",
  "form-of adjective · form-of noun · own adjective · own noun · two blocks about one word · 3+ readings · links": "poltrone",
  "form-of adjective · form-of noun · own verb · two blocks about one word · 3+ readings · links": "sumere",
  "form-of adjective · form-of noun · own verb form record · 3+ readings · links": "morti",
  "form-of adjective · form-of other · 2 readings, 2+ words · links": "parecchie",
  "form-of adjective · form-of other · own verb form record · two blocks about one word · verb-form · 3+ readings · links": "diversi",
  "form-of adjective · own adjective · 2 readings, 1 word · no links": "imbelle",
  "form-of adjective · own noun · 2 readings, 1 word · no links": "protettrici",
  "form-of adjective · own noun · own noun form record · 3+ readings · links": "carbonara",
  "form-of adjective · own noun · own verb form record · verb-form · 3+ readings · links": "calma",
  "form-of adjective · own other · 3+ readings · links": "Gaia",
  "form-of adjective · own verb · verb-form · 3+ readings · links": "guasti",
  "form-of adjective · two blocks about one word · 2 readings, 1 word · no links": "blasfeme",
  "form-of noun · form-of verb · own noun · 3+ readings · links": "scapigliata",
  "form-of noun · own adjective · own adjective form record · own noun · 3+ readings · links": "burlone",
  "form-of noun · own adjective · own verb · 3+ readings · links": "scolare",
  "form-of noun · own noun · own other · 3+ readings · links": "colle",
  "form-of noun · own noun · own verb form record · 3+ readings · links": "sparata",
  "form-of noun · own verb · 3+ readings · links": "tessere",
  "form-of verb · own adjective · 3+ readings · links": "rinvolto",
  "form-of verb · own adjective · own noun · own other · 3+ readings · links": "sommesso",
  "form-of verb · own adjective · own noun · own other · verb-form · 3+ readings · links": "manifesto",
  "form-of verb · own adjective form record · own noun form record · 3+ readings · links": "spiccioli",
  "form-of verb · own other · 3+ readings · links": "Vania",
  "grid-form · 2 readings, 2+ words · links": "ragazzi",
  "grid-form · 3+ readings · links": "soverchie",
  "own adjective · own noun form record · verb-form · 3+ readings · links": "scarti",
  "own adjective · own verb · 3+ readings · links": "giubilare",
  "own adjective · verb-form · 2 readings, 1 word · no links": "sfocato",
  "own adjective form record · own noun · 3+ readings · links": "tanghera",
  "own adjective form record · own noun · own verb form record · 3+ readings · links": "buttata",
  "own adjective form record · own verb form record · 2 readings, 1 word · no links": "producenti",
  "own adjective form record · own verb form record · verb-form · 3+ readings · links": "logorate",
  "own noun · own noun form record · 3+ readings · links": "pome",
  "own noun · own noun form record · verb-form · 3+ readings · links": "cestino",
  "own noun · own other · own verb · 3+ readings · links": "dovere",
  "own noun form record · verb-form · 3+ readings · links": "assistiti",
  "own other · own verb form record · 2 readings, 1 word · no links": "to",
  "expression page · expression form · expression page, 1 reading · no links": "zuppe inglese",
  "expression page · expression form · expression page, 2 readings · no links": "zuppa inglesi",
  "expression page · expression form · expression page, 3+ readings · no links": "servizio sanitario nazionali",
  "expression page · expression form · expression own · expression page, 2 readings · no links": "Torre fari",
  "expression page · expression form · expression own · expression page, 3+ readings · no links": "Venerdì santi",
  "another word's record · own adjective · 1 reading · no links": "litiganti",
  "another word's record · own noun · 1 reading · no links": "perossidi di idrogeno",
  "another word's record · own other · 3+ readings · links": "alberi a camme",
};
